server:
  port: 9001
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true #是否打印sql语句
    generate-ddl: true # 是否自动建表
    database: mysql #jpa链接的数据库类型

eureka:
  client:
    register-with-eureka: true  #作为客户端需要注册到Eureka
    fetch-registry: true #作为客户端需要从Eureka获取注册信息
    service-url:      #客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka   #,http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true     #优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    lease-renewal-interval-in-seconds: 5      # 修改续约间隔时间
    lease-expiration-duration-in-seconds: 10  # 修改服务失效时间